mj:
  account-store-type: in_memory
  accounts:
    - guild-id: 662267976984297473
      channel-id: 997261020609384458
      user-token: ODE3NDQwMzg3MjMyMzAxMTE3.G7Hdhl.N42j_PU65Gp-49TvZwkws15zl5ALqKQ71kouqw
      mj-bot-channel-id: xxx
      session-id: 9c4055428e13bcbf2248a6b36084c5f3
      user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
      core-size: 3
      queue-size: 10
      timeout-minutes: 5 
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  translate-zh-way: null
  error-desc:
    - en: "against our community standards"
      zh: "可能包含违规信息"
