mj:
  account-store-type: in_memory
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  translate-zh-way: null
  error-desc:
    - en: "against our community standards"
      zh: "可能包含违规信息"
